### ISSUE TITLE
[vite] Internal server error: Cannot read properties of undefined (reading 'Client')

### ISSUE THREAD

**Issue by bbigras** [neondatabase/serverless#5]
# Steps to reproduce

- clone https://github.com/bbigras/test-qwik-neon
- npm install
- npm run build

  
```
16 h 14 min 13 s [vite] Internal server error: Cannot read properties of undefined (reading 'Client')
  File: /home/bbigras/dev/test-qwik-neon/src/routes/index.tsx:13:21
  11 |   *  */
  12 |  export default component$(() => {
  13 |    const client = new Client("http://127.0.0.1");
     |                      ^
  14 |    /* console.log("client", client); */
  15 |
      at routes_component_xYL1qOwPyDI (/home/bbigras/dev/test-qwik-neon/src/routes/index.tsx:13:21)
      at invoke (file:///home/bbigras/dev/test-qwik-neon/node_modules/@builder.io/qwik/core.mjs:706:26)
      at file:///home/bbigras/dev/test-qwik-neon/node_modules/@builder.io/qwik/core.mjs:6348:28
      at async Promise.all (index 0)
      at async Promise.all (index 0)
      at async renderRoot (file:///home/bbigras/dev/test-qwik-neon/node_modules/@builder.io/qwik/core.mjs:6840:5)
      at async renderSSR (file:///home/bbigras/dev/test-qwik-neon/node_modules/@builder.io/qwik/core.mjs:6836:5)
      at async Proxy.renderToStream (file:///home/bbigras/dev/test-qwik-neon/node_modules/@builder.io/qwik/server.mjs:632:3)
      at async /home/bbigras/dev/test-qwik-neon/node_modules/@builder.io/qwik/optimizer.cjs:1763:28
```

_Originally posted by @bbigras in https://github.com/neondatabase/serverless/issues/1#issuecomment-1397619235_

**Comment by bbigras** [comment]
I don't have the problem anymore.
